// Starter exercise library, added to your account the first time you open
// Workouts. [name, muscle group, equipment, exercise type]
const W = 'weight_reps'
const BW = 'bodyweight_reps'
const WBW = 'weighted_bodyweight'
const ABW = 'assisted_bodyweight'
const DUR = 'duration'
const DIST = 'distance_duration'

export const SEED_EXERCISES = [
  // Chest
  ['Bench Press (Barbell)', 'Chest', 'Barbell', W],
  ['Incline Bench Press (Barbell)', 'Chest', 'Barbell', W],
  ['Decline Bench Press (Barbell)', 'Chest', 'Barbell', W],
  ['Bench Press (Dumbbell)', 'Chest', 'Dumbbell', W],
  ['Incline Bench Press (Dumbbell)', 'Chest', 'Dumbbell', W],
  ['Chest Fly (Dumbbell)', 'Chest', 'Dumbbell', W],
  ['Cable Fly', 'Chest', 'Cable', W],
  ['Chest Press (Machine)', 'Chest', 'Machine', W],
  ['Pec Deck (Machine)', 'Chest', 'Machine', W],
  ['Push Up', 'Chest', 'Bodyweight', BW],
  ['Chest Dip', 'Chest', 'Bodyweight', BW],
  ['Chest Dip (Weighted)', 'Chest', 'Bodyweight', WBW],
  // Back
  ['Deadlift (Barbell)', 'Back', 'Barbell', W],
  ['Bent Over Row (Barbell)', 'Back', 'Barbell', W],
  ['Pendlay Row (Barbell)', 'Back', 'Barbell', W],
  ['T-Bar Row', 'Back', 'Barbell', W],
  ['Dumbbell Row', 'Back', 'Dumbbell', W],
  ['Lat Pulldown (Cable)', 'Back', 'Cable', W],
  ['Seated Cable Row', 'Back', 'Cable', W],
  ['Seated Row (Machine)', 'Back', 'Machine', W],
  ['Straight Arm Pulldown (Cable)', 'Back', 'Cable', W],
  ['Pull Up', 'Back', 'Bodyweight', BW],
  ['Pull Up (Weighted)', 'Back', 'Bodyweight', WBW],
  ['Pull Up (Assisted)', 'Back', 'Machine', ABW],
  ['Chin Up', 'Back', 'Bodyweight', BW],
  ['Chin Up (Assisted)', 'Back', 'Machine', ABW],
  ['Back Extension', 'Back', 'Bodyweight', BW],
  ['Rack Pull (Barbell)', 'Back', 'Barbell', W],
  ['Shrug (Barbell)', 'Back', 'Barbell', W],
  ['Shrug (Dumbbell)', 'Back', 'Dumbbell', W],
  // Shoulders
  ['Overhead Press (Barbell)', 'Shoulders', 'Barbell', W],
  ['Shoulder Press (Dumbbell)', 'Shoulders', 'Dumbbell', W],
  ['Shoulder Press (Machine)', 'Shoulders', 'Machine', W],
  ['Arnold Press (Dumbbell)', 'Shoulders', 'Dumbbell', W],
  ['Lateral Raise (Dumbbell)', 'Shoulders', 'Dumbbell', W],
  ['Lateral Raise (Cable)', 'Shoulders', 'Cable', W],
  ['Front Raise (Dumbbell)', 'Shoulders', 'Dumbbell', W],
  ['Rear Delt Fly (Dumbbell)', 'Shoulders', 'Dumbbell', W],
  ['Reverse Pec Deck (Machine)', 'Shoulders', 'Machine', W],
  ['Face Pull (Cable)', 'Shoulders', 'Cable', W],
  ['Upright Row (Barbell)', 'Shoulders', 'Barbell', W],
  // Biceps
  ['Bicep Curl (Barbell)', 'Biceps', 'Barbell', W],
  ['Bicep Curl (Dumbbell)', 'Biceps', 'Dumbbell', W],
  ['EZ Bar Curl', 'Biceps', 'EZ Bar', W],
  ['Hammer Curl (Dumbbell)', 'Biceps', 'Dumbbell', W],
  ['Preacher Curl', 'Biceps', 'EZ Bar', W],
  ['Incline Curl (Dumbbell)', 'Biceps', 'Dumbbell', W],
  ['Cable Curl', 'Biceps', 'Cable', W],
  ['Concentration Curl', 'Biceps', 'Dumbbell', W],
  // Triceps
  ['Triceps Pushdown (Cable)', 'Triceps', 'Cable', W],
  ['Overhead Triceps Extension (Cable)', 'Triceps', 'Cable', W],
  ['Overhead Triceps Extension (Dumbbell)', 'Triceps', 'Dumbbell', W],
  ['Skull Crusher (EZ Bar)', 'Triceps', 'EZ Bar', W],
  ['Close Grip Bench Press', 'Triceps', 'Barbell', W],
  ['Triceps Kickback (Dumbbell)', 'Triceps', 'Dumbbell', W],
  ['Triceps Dip', 'Triceps', 'Bodyweight', BW],
  ['Triceps Dip (Assisted)', 'Triceps', 'Machine', ABW],
  // Forearms
  ['Wrist Curl (Dumbbell)', 'Forearms', 'Dumbbell', W],
  ['Reverse Curl (Barbell)', 'Forearms', 'Barbell', W],
  ["Farmer's Carry", 'Forearms', 'Dumbbell', DUR],
  // Quads
  ['Squat (Barbell)', 'Quads', 'Barbell', W],
  ['Front Squat (Barbell)', 'Quads', 'Barbell', W],
  ['Leg Press (Machine)', 'Quads', 'Machine', W],
  ['Hack Squat (Machine)', 'Quads', 'Machine', W],
  ['Leg Extension (Machine)', 'Quads', 'Machine', W],
  ['Goblet Squat', 'Quads', 'Dumbbell', W],
  ['Bulgarian Split Squat (Dumbbell)', 'Quads', 'Dumbbell', W],
  ['Lunge (Dumbbell)', 'Quads', 'Dumbbell', W],
  ['Walking Lunge (Dumbbell)', 'Quads', 'Dumbbell', W],
  ['Step Up (Dumbbell)', 'Quads', 'Dumbbell', W],
  ['Bodyweight Squat', 'Quads', 'Bodyweight', BW],
  // Hamstrings
  ['Romanian Deadlift (Barbell)', 'Hamstrings', 'Barbell', W],
  ['Romanian Deadlift (Dumbbell)', 'Hamstrings', 'Dumbbell', W],
  ['Lying Leg Curl (Machine)', 'Hamstrings', 'Machine', W],
  ['Seated Leg Curl (Machine)', 'Hamstrings', 'Machine', W],
  ['Good Morning (Barbell)', 'Hamstrings', 'Barbell', W],
  ['Nordic Curl', 'Hamstrings', 'Bodyweight', BW],
  // Glutes
  ['Hip Thrust (Barbell)', 'Glutes', 'Barbell', W],
  ['Glute Bridge', 'Glutes', 'Bodyweight', BW],
  ['Sumo Deadlift (Barbell)', 'Glutes', 'Barbell', W],
  ['Cable Kickback', 'Glutes', 'Cable', W],
  ['Hip Abduction (Machine)', 'Glutes', 'Machine', W],
  // Calves
  ['Standing Calf Raise (Machine)', 'Calves', 'Machine', W],
  ['Seated Calf Raise (Machine)', 'Calves', 'Machine', W],
  ['Calf Raise (Dumbbell)', 'Calves', 'Dumbbell', W],
  // Core
  ['Plank', 'Core', 'Bodyweight', DUR],
  ['Side Plank', 'Core', 'Bodyweight', DUR],
  ['Crunch', 'Core', 'Bodyweight', BW],
  ['Sit Up', 'Core', 'Bodyweight', BW],
  ['Hanging Leg Raise', 'Core', 'Bodyweight', BW],
  ['Cable Crunch', 'Core', 'Cable', W],
  ['Ab Wheel Rollout', 'Core', 'Other', BW],
  ['Russian Twist', 'Core', 'Bodyweight', BW],
  ['Dead Bug', 'Core', 'Bodyweight', BW],
  // Full body
  ['Kettlebell Swing', 'Full body', 'Kettlebell', W],
  ['Burpee', 'Full body', 'Bodyweight', BW],
  ['Clean and Press (Barbell)', 'Full body', 'Barbell', W],
  // Cardio
  ['Running', 'Cardio', 'None', DIST],
  ['Treadmill', 'Cardio', 'Machine', DIST],
  ['Walking', 'Cardio', 'None', DIST],
  ['Cycling', 'Cardio', 'None', DIST],
  ['Stationary Bike', 'Cardio', 'Machine', DIST],
  ['Rowing Machine', 'Cardio', 'Machine', DIST],
  ['Swimming', 'Cardio', 'None', DIST],
  ['Elliptical', 'Cardio', 'Machine', DUR],
  ['Stair Climber', 'Cardio', 'Machine', DUR],
  ['Jump Rope', 'Cardio', 'Other', DUR],
]
